[package]
name = "ruby-version-badger"
version = "0.1.1"
target = "1.23.0"
authors = ["James Smith <james@floppy.org.uk>"]

[dependencies]
iron = "0.5.*"
router = "*"
staticfile = "*"
futures = "0.1"
hyper = "0.11"
hyper-rustls = "*"
tokio-core = "0.1"
regex = "*"
log = "0.3"
env_logger = "0.3"
